### ISSUE TITLE
Can't reproduce fig 5 because of data missing

### ISSUE THREAD

**Issue by JustMuteAll** [david-klindt/NIPS2017#7]
In the fig5.ipynb,there is one line code:"Data=np.load('/gpfs01/bethge/home/dklindt/David/publish/data.npz')"
Obviously,this is a local path,so when I run the code,I can't load the data file,and neither can I find corresponding data file in the github repositories.Can you please fix the code,or add the data file needed for reproducing fig 5?

**Comment by aecker** [comment]
@david-klindt can you look into this? This seems to be your code and I can't find the file, either.

**Comment by david-klindt** [comment]
I will see if I still have a local copy of those files (after the ICLR deadline). I believe the gpfs01 data was written to tape, so that might be tricky to excavate. Fixing the code would be a bigger tasks since this was still done in TF1.

**Comment by ZeroAda** [comment]
Hi, @david-klindt , I'm also reproducing fig5 experiments. Could you please look into the data missed here? Thank you a lot!

**Comment by david-klindt** [comment]
We just tried, but the files are very difficult to access (written to tape) at this point. To reproduce the results, please follow the instructions in the paper to sample responses from 'VGG Conv2' to 44x44 images. Thank you!
